# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Bio
    url: /bio
    weight: 11

  - name: Research
    url: research/ 
    # url: projects/
    weight: 12

  - name: Projects
    url: projects/
    weight: 13

  - name: Papers
    url: /#papers
    weight: 14

  - name: Talks
    url: /#talks
    weight: 15

  - name: News
    url: /#news
    weight: 16

  - name: Experience
    url: experience/
    weight: 20



  # - name: Teaching
  #   url: teaching/
  #   weight: 40
